version: 2

project_name: resolume-timecode

before:
  hooks:
    - go install github.com/tc-hib/go-winres@latest
    - go mod download
    - bash -c "rsvg-convert -h 256 images/logo.svg > winres/icon.png"
    - bash -c "rsvg-convert -h 32 images/logo.svg > images/favicon.png"
    - bash -c "rsvg-convert -h 256 images/logo.svg > images/logo.png"
    - go-winres make --product-version=git-tag --file-version=git-tag

builds:
  - id: darwin-amd64
    goos: [darwin]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.Date={{.CommitDate}}
    mod_timestamp: '{{ .CommitTimestamp }}'

  - id: darwin-arm64
    goos: [darwin]
    goarch: [arm64]
    env:
      - CGO_ENABLED=1
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.Date={{.CommitDate}}
    mod_timestamp: '{{ .CommitTimestamp }}'

  - id: windows
    goos: [windows]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.Date={{.CommitDate}}
      - -H=windowsgui
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      post: upx {{ .Path }}

universal_binaries:
  - id: darwin-universal
    ids: [darwin-amd64, darwin-arm64]
    name_template: resolume-timecode
    replace: true
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      post:
        - sh macos.sh resolume-timecode images/logo.svg "me.chabad360.resolume-timecode" {{ .Major }} {{ .Minor }}
        - cp {{ .Path }} resolume-timecode.app/Contents/MacOS/

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^ci:'
      - '^docs?:'
      - '^tests?:'

release:
  github:
    owner: calebweixun
    name: resolume-timecode
  draft: true
  prerelease: auto

archives:
  - id: darwin
    ids: [darwin-universal]
    formats: [zip]
    wrap_in_directory: true
    name_template: '{{ .ProjectName }}_{{ .Version }}_macOS_Universal'
    files:
      - LICENSE
      - README.MD
      - resolume-timecode.app

  - id: windows
    ids: [windows]
    formats: [zip]
    wrap_in_directory: true
    name_template: '{{ .ProjectName }}_{{ .Version }}_Windows_{{ .Arch }}'
